name: Go & Python CI for ClassConnect API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2

      - name: Install Go dependencies
        run: go mod tidy

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Definir variables de entorno
        run: echo "MONGO_URI=mongodb://localhost:27017" >> $GITHUB_ENV

      - name: Esperar a que MongoDB esté listo
        run: |
          for i in {1..10}; do
            nc -z localhost 27017 && echo "MongoDB está listo" && exit 0
            echo "Esperando a MongoDB..."
            sleep 3
          done
          echo "MongoDB no se inició a tiempo" && exit 1

      - name: Run Go unit tests
        run: go test -v ./backend/test

      - name: Run Python unit tests
        run: pytest ./backend/test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.out

        
